version: '1.0'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gonav
    ports:
      - "3306:3306"
    networks:
      - gonav

  springboot:
    build: .
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MAIL_HOST: smtp.126.com
      MAIL_USERNAME: ruanzhutool@126.com
      MAIL_PASSWORD: TJBYKZIDQIIFGSNP
      ADMIN_EMAIL: rongxingyang@outlook.com
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - gonav

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    networks:
      - gonav

  nginx:
    image: nginx:latest
    ports:
      - "80:80"       
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - springboot
    networks:
      - gonav

networks:
  gonav:
    driver: bridge
