# application.yml - 通用配置
server:
  port: 8080
spring:
  profiles:
    active: dev # TODO 默认使用 dev 配置
  application:
    name: gonav-server
  error:
    whitelabel:
      enabled: false
    include-message: never
    include-binding-errors: never
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
logging:
  level:
    org.springframework.security: DEBUG
    com.dawn.gonav.authentication: DEBUG